#!/bin/bash
# misc term
alias cls="clear"
alias vim="nvim"

# prettier outputs by default
alias ls="ls -CF --color=auto"
alias df="df -ahiT --total"
alias mkdir="mkdir -p"
alias ps="ps auxf"
alias wget="wget -c"
alias grep='grep --color=auto'
alias bc="bc -q"

# git
alias gits="git status"
alias gita="git add"
alias gitcl="git clone"
alias gitcm="git commit -m"
alias gitch="git checkout"
alias gitsh="git shortlog"
alias gitl="git log --oneline --color --graph"
alias gitb="git branch"
alias gitp="git push"
alias gitf="git fetch"

# random
alias userlist="cut -d: -f1 /etc/passwd"
alias fhere="find . -name "
alias free="free -mt"
alias psgrep="ps aux | grep -v grep | grep -i -e VSZ -e"
alias histg="history | grep"
alias myip="curl http://ipecho.net/plain; echo"
alias logs="find /var/log -type f -exec file {} \; | grep 'text' | cut -d' ' -f1 | sed -e's/:$//g' | grep -v '[0-9]$' | xargs tail -f"
alias folders='find . -maxdepth 1 -type d -print0 | xargs -0 du -sk | sort -rn'
alias restartnet='sudo systemctl restart NetworkManager'
alias dockertek='docker run --rm -it -v $PWD:/home/ -w /home epitechcontent/epitest-docker /bin/bash'

# most used
alias sdn="shutdown -h now"
alias upd="sudo pacman -Syyu --noconfirm && yay -Syyu --noconfirm"

# C stuff
alias clean_repo="rm *gc* unit_tests; make fclean"
alias mktr="clean_repo; make tests_run_clean"
alias vg="valgrind -v --leak-check=full --show-leak-kinds=all --log-file=valgrind.txt"
