#!/bin/bash
#~ useful bash functions

# Creates an archive (*.tar.gz) from given directory.
function maketar() { tar cvzf "${1%%/}.tar.gz"  "${1%%/}/"; }

# Create a ZIP archive of a file or folder.
function makezip() { zip -r "${1%%/}.zip" "$1" ; }

#finds the package installer used by the installation
get_installer () {
    which zypper &> /dev/null && echo "sudo zypper -y install"
    which pacman &> /dev/null && echo "sudo pacman --noconfirm --needed -S"
    which dnf &> /dev/null && echo "sudo dnf -y install"
    which apt &> /dev/null && echo "sudo apt -y install"
}
